# This file stores configurations for your Shopify app.

NAME = "Pixelfox facebook app integration"
SCOPES = "read_products,write_products,read_price_rules,write_price_rules,read_discounts,write_discounts,read_orders,write_orders,read_themes,write_themes,read_online_store_pages,read_content,write_content,read_script_tags,write_script_tags,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_checkouts"