<?php

namespace App\Http\Controllers;

    
use Illuminate\Http\Request;
use FacebookAds\Object\AdsPixel;
use FacebookAds\Api;
use FacebookAds\Logger\CurlLogger;
use FacebookAds\Object\AdAccount;
use Auth;
use Redirect;
use Session;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

 

 

class FacebookController extends Controller
{
    public function interest(){
         

        
 


//////   SHORT ACCESS TOKEN  GENERATED BY GRAPH EXPLORER TOOL //////////


       
        // $accessToken = "EAAFssVZC2cqoBADZChAG6a4hrDwfzWlu0fKlEBRJTd2zDnJjktFjAfQMsAoUaOerwBp9PlwEo4nwukQmAKug1hc1cAvwIYTWCdK2DFZATFx1CvV3ujOuMOFYaZCxHOLqUuwwaleZBHOiJHxl56V1iTXD1cwWZClCwW5XBdt7ZBiOkWIrY8TjiNylupxAmoIrIlhCt7801yxJTS7AracZA7bU";
        
        
        

    try{


        $response1 = Http::get("https://graph.facebook.com/v12.0/oauth/access_token?grant_type=fb_exchange_token&client_id=400984051708586&client_secret=05894581e48867ddb78da2bc7ac6cfaa&fb_exchange_token=$accessToken");
         
         
        $LiveLiveAccessToken = $response1['access_token'];


    }catch (\Exception $e) {

        // return $e->getMessage();
    }


//////   LONGLIVE ACCESS TOKEN  GET BY GRAPH API  //////////
     
        // $LiveLiveAccessToken=
        // "EAAFssVZC2cqoBAKET4ZAnFRLxdJdNvLQTUgSxrgMeFCrCWtlhzUfnvgjHvbp21uSkyHpCumZAx6woMk4KiZBAsIxOm8KXf4hmN9PYxYyZC4LygfPtpcrdDPlZCGWcTAVoIK1TipZCYZBDQZCipz9C8aRNgV23vlZBn47siXRy0qV9lTwZDZD";

     
        // return $LiveAccessToken;
         



        $query = request('q');
        $query = ucwords($query);
         
        $query=json_encode($query);
    
        $list=[$query];
        
         
        $type = request('type');
        if($type=="adinterestsuggestion&interest_list=['type']"){
             $type = request('type'); 
             $type=  explode("&", $type)[0];
             
             $list="interest_list=[$query]";
             
              
             
            //  $response = Http::get("https://graph.facebook.com/v12.0/search?type={$type}&interest_list=[$query]&access_token={$LiveLiveAccessToken}");


            $response = Http::get("https://graph.facebook.com/v12.0/search?type={$type}&interest_list=[$query]&access_token=4523632734389862|396a9f01aab1a44b37b18038ce1f278c");
        
              $result = $response->json();
        }else{
             
            $type = request('type'); 
            $response = Http::get("https://graph.facebook.com/v12.0/search?type={$type}&q=[$query]&limit=1000&access_token=4523632734389862|396a9f01aab1a44b37b18038ce1f278c");
        
            $result = $response->json();
        }
        
         
        
         
    
        
        return response()->json($result);
    }
}