name: deploy-to-staging-server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: composer:2.3
    steps:
      - uses: actions/checkout@v3
      - run: rm composer.json composer.lock
      - run: composer require laravel/envoy --dev