name: deploy-to-staging-server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: composer:2.3
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        SSHKEY: ${{ secrets.DEPLOYER_KEY }}
    - run: ssh -T git@github.com || true
    - run: composer require laravel/envoy --dev
    - run:  ./vendor/bin/envoy run deploy --password ${{ secrets.GITHUB.token }}
