name: deploy-to-staging-server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: composer:2.3
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls
      - run: 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - run: eval $(ssh-agent -s)
      - run: ssh-add ${{ secrets.DEPLOYER_KEY }}
      - run: mkdir -p ~/.ssh
#       - run: composer require laravel/envoy --dev
