name: deploy-to-staging-server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: composer:2.3
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls
      - run: echo ${{ secrets.DEPLOYER_KEY }}
#       - run: composer require laravel/envoy --dev
